name: pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (no submodules)
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload files
        uses: actions/upload-pages-artifact@v1
        with:
          path: .    # upload everything at the repo root, including index.html

      - name: Deploy
        uses: actions/deploy-pages@v1
